language: java
# Para instalar openjdk11 sin problemas (https://travis-ci.community/t/install-of-openjdk11-is-failing-again/3061/16)
dist: trusty
jdk:
  - openjdk11

services:
  - docker

before_install:
  - docker pull ghcr.io/guillergood/dailyreport-2.0:latest

script:
  # Script para que ejecute los test con la regla por defecto
  # Con mvn clean package ejecuta todos los tests y el coverage
  #- mvn test
  - docker run -t -v "$(pwd)":/app/test guillergood/dailyreport-2.0:latest

#after_success:
  # report coverage to codecov.io
  #- bash <(curl https://codecov.io/bash)