language: java
# Para instalar openjdk11 sin problemas (https://travis-ci.community/t/install-of-openjdk11-is-failing-again/3061/16)
dist: xenial
jdk:
  - openjdk11
  
script:
  # Script para que ejecute los test con la regla por defecto
  # Con mvn clean package ejecuta todos los tests y el coverage
  - mvn verify

notifications:
  email:
    recipients:
      - guillergood@gmail.com
    on_success: never # default: change
    on_failure: always # default: always

after_success:
  # report coverage to codecov.io
  - bash <(curl https://codecov.io/bash)
