language: java
# Para instalar openjdk11 sin problemas (https://travis-ci.community/t/install-of-openjdk11-is-failing-again/3061/16)
dist: xenial
jdk:
  - openjdk11
script:
  # Script para que ejecute los test con la regla por defecto
  - make