language: java
# Para instalar openjdk11 sin problemas (https://travis-ci.community/t/install-of-openjdk11-is-failing-again/3061/16)
dist: trusty
jdk:
  - openjdk11

script:
  # Script para que ejecute los test con la regla por defecto
  # Con mvn clean package ejecuta todos los tests y el coverage
  - mvn clean package
  - mvn cobertura:cobertura

after_success:
  # report coverage to codecov.io
  - bash <(curl https://codecov.io/bash)