version: '3.3'

services:
  mongoanimal:
    image: 'bitnami/mongodb:latest'
    container_name: "mongoanimal"
    ports:
      - '${{ PORT_DB_ANIMAL }}:${{ PORT_DB_DEFAULT }}'
  mongocuidador:
    image: 'bitnami/mongodb:latest'
    container_name: "mongocuidador"
    ports:
      - '${{ PORT_DB_CUIDADOR }}:${{ PORT_DB_DEFAULT }}'
  mongoburocratico:
    image: 'bitnami/mongodb:latest'
    container_name: "mongoburocratico"
    ports:
      - '${{ PORT_DB_BUROCRATICO }}:${{ PORT_DB_DEFAULT }}'
  mongoapi:
    image: 'bitnami/mongodb:latest'
    container_name: "mongoapi"
    ports:
      - '${{ PORT_DB_API }}:${{ PORT_DB_DEFAULT }}'
  animal:
    build: ./src/Animal
    image: dailyreport-animal
    container_name: "animal"
    links:
      - mongoanimal
    environment:
      - ADDITIONAL_OPTS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=${{ PORT_HOST_ANIMAL }}
      - MONGODB_HOST=mongoanimal
      - MONGODB_PORT=${{ PORT_DB_DEFAULT }}

    depends_on:
      - mongoanimal
    ports:
      - "${{ PORT_HOST_ANIMAL }}:${{ PORT_HOST_ANIMAL }}"
  cuidador:
    build: ./src/Cuidador
    image: dailyreport-cuidador
    container_name: "cuidador"
    links:
      - mongocuidador
    environment:
      - ADDITIONAL_OPTS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=${{ PORT_HOST_CUIDADOR }}
      - MONGODB_HOST=mongocuidador
      - MONGODB_PORT=${{ PORT_DB_DEFAULT }}

    depends_on:
      - mongocuidador
    ports:
      - "${{ PORT_HOST_CUIDADOR }}:${{ PORT_HOST_CUIDADOR }}"

  burocratico:
    build: ./src/Burocratico
    image: dailyreport-burocratico
    container_name: "burocratico"
    links:
      - mongoburocratico
    environment:
      - ADDITIONAL_OPTS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=${{ PORT_HOST_BUROCRATICO }}
      - MONGODB_HOST=mongoburocratico
      - MONGODB_PORT=${{ PORT_DB_DEFAULT }}

    depends_on:
      - mongoburocratico
      - cuidador
      - animal
    ports:
      - "${{ PORT_HOST_BUROCRATICO }}:${{ PORT_HOST_BUROCRATICO }}"
  api:
    build: ./src/API
    image: dailyreport-api
    container_name: "api"
    links:
      - mongoapi
    environment:
      - ADDITIONAL_OPTS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=${{ PORT_HOST_API }}
    depends_on:
      - mongoapi
      - cuidador
      - animal
      - burocratico