version: 2.1
jobs:
    test:
        docker: #Descarga de Docker la imagen del contenedor creado
            - image: guillergood/dailyreport-2.0:latest
        steps:
            - checkout
            # Ejecuta la orden test de maven
            - run: gradle test

workflows:
    test_dailyreport:
        jobs:
            - test
