version: 2.2
jobs:
    test:
        docker: #Descarga de Docker la imagen del contenedor creado
            - image: guillergood/dailyreport-2.0:latest
        steps:
            - checkout
            # Ejecuta la orden verify de maven
            - run: mvn verify

workflows:
    test_dailyreport:
        jobs:
            - test
