version: 2.1

# Tasks definition
jobs:
    test:
        docker:
            # Project's Docker image in Docker Hub
            - image: guillergood/dailyreport-2.0:latest
        steps:
            - checkout
            # Launch tests using the task manager
            - run: mvn verify

# Workflows of CircleCI
workflows:
    test_project:
        jobs:
            - test
